{{- if .Values.orion.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orion
spec:
  selector:
    app: orion
  ports:
    - protocol: TCP
      port: {{ .Values.orion.port }}
      targetPort: {{ .Values.orion.port }}
  type: ClusterIP
{{- end }}
